import type { CollectionBeforeValidateHook } from 'payload'

import { ValidationError } from 'payload'

/**
 * Slugs are unique per `{ site, locale }` — two customers may both own `/about`,
 * one customer may not own it twice in the same language.
 *
 * This is application-level because neither available mechanism works here:
 * - the multi-tenant plugin does not enforce slug uniqueness at all;
 * - a DB compound unique index on `(site, slug)` is rejected by the Postgres
 *   adapter — `Compound indexes within localized and non localized fields are not
 *   supported in SQL` — and `slug` is localized while `site` is not.
 *
 * So `slugField` is configured with `disableUnique: true` and this runs instead.
 * Being a check-then-write, it races under concurrent creates; the losing write
 * produces a duplicate rather than an error. Acceptable: slugs are typed by hand
 * in an admin panel, not generated by machines.
 */
export const uniqueSlugPerSite: CollectionBeforeValidateHook = async ({
  collection,
  data,
  originalDoc,
  req,
}) => {
  const slug = data?.slug ?? originalDoc?.slug
  const site = data?.site ?? originalDoc?.site
  // A missing site is the tenant field's own validation error, not ours.
  const siteId = typeof site === 'object' && site !== null ? site.id : site

  if (!slug || !siteId) return data

  const { totalDocs } = await req.payload.count({
    collection: collection.slug,
    // The comparison is per locale, so it must run in the locale being written.
    // `'all'` is a read-only pseudo-locale that `count` does not accept.
    locale: req.locale === 'all' ? undefined : req.locale,
    // A tenant user cannot read the sibling document that collides with theirs,
    // so an access-controlled count would report zero and let the clash through.
    overrideAccess: true,
    req,
    where: {
      and: [
        { site: { equals: siteId } },
        { slug: { equals: slug } },
        ...(originalDoc?.id ? [{ id: { not_equals: originalDoc.id } }] : []),
      ],
    },
  })

  if (totalDocs > 0) {
    throw new ValidationError({
      collection: collection.slug,
      errors: [
        {
          message: `نشانی «${slug}» در این زبان از قبل استفاده شده است.`,
          path: 'slug',
        },
      ],
      req,
    })
  }

  return data
}
