import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  CREATE TABLE "payload_mcp_api_keys" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"user_id" uuid NOT NULL,
  	"label" varchar,
  	"description" varchar,
  	"pages_find" boolean DEFAULT false,
  	"pages_create" boolean DEFAULT false,
  	"pages_update" boolean DEFAULT false,
  	"pages_delete" boolean DEFAULT false,
  	"posts_find" boolean DEFAULT false,
  	"posts_create" boolean DEFAULT false,
  	"posts_update" boolean DEFAULT false,
  	"posts_delete" boolean DEFAULT false,
  	"media_find" boolean DEFAULT false,
  	"media_create" boolean DEFAULT false,
  	"media_update" boolean DEFAULT false,
  	"media_delete" boolean DEFAULT false,
  	"categories_find" boolean DEFAULT false,
  	"categories_create" boolean DEFAULT false,
  	"categories_update" boolean DEFAULT false,
  	"categories_delete" boolean DEFAULT false,
  	"users_find" boolean DEFAULT false,
  	"users_create" boolean DEFAULT false,
  	"users_update" boolean DEFAULT false,
  	"users_delete" boolean DEFAULT false,
  	"sites_find" boolean DEFAULT false,
  	"sites_create" boolean DEFAULT false,
  	"sites_update" boolean DEFAULT false,
  	"sites_delete" boolean DEFAULT false,
  	"api_keys_find" boolean DEFAULT false,
  	"api_keys_create" boolean DEFAULT false,
  	"api_keys_update" boolean DEFAULT false,
  	"api_keys_delete" boolean DEFAULT false,
  	"storage_connections_find" boolean DEFAULT false,
  	"storage_connections_create" boolean DEFAULT false,
  	"storage_connections_update" boolean DEFAULT false,
  	"storage_connections_delete" boolean DEFAULT false,
  	"theme_find" boolean DEFAULT false,
  	"theme_create" boolean DEFAULT false,
  	"theme_update" boolean DEFAULT false,
  	"theme_delete" boolean DEFAULT false,
  	"site_branding_find" boolean DEFAULT false,
  	"site_branding_create" boolean DEFAULT false,
  	"site_branding_update" boolean DEFAULT false,
  	"site_branding_delete" boolean DEFAULT false,
  	"header_find" boolean DEFAULT false,
  	"header_create" boolean DEFAULT false,
  	"header_update" boolean DEFAULT false,
  	"header_delete" boolean DEFAULT false,
  	"footer_find" boolean DEFAULT false,
  	"footer_create" boolean DEFAULT false,
  	"footer_update" boolean DEFAULT false,
  	"footer_delete" boolean DEFAULT false,
  	"products_find" boolean DEFAULT false,
  	"products_create" boolean DEFAULT false,
  	"products_update" boolean DEFAULT false,
  	"products_delete" boolean DEFAULT false,
  	"orders_find" boolean DEFAULT false,
  	"orders_create" boolean DEFAULT false,
  	"orders_update" boolean DEFAULT false,
  	"orders_delete" boolean DEFAULT false,
  	"store_find" boolean DEFAULT false,
  	"store_create" boolean DEFAULT false,
  	"store_update" boolean DEFAULT false,
  	"store_delete" boolean DEFAULT false,
  	"payment_gateways_find" boolean DEFAULT false,
  	"payment_gateways_create" boolean DEFAULT false,
  	"payment_gateways_update" boolean DEFAULT false,
  	"payment_gateways_delete" boolean DEFAULT false,
  	"cdn_zones_find" boolean DEFAULT false,
  	"cdn_zones_create" boolean DEFAULT false,
  	"cdn_zones_update" boolean DEFAULT false,
  	"cdn_zones_delete" boolean DEFAULT false,
  	"cdn_events_find" boolean DEFAULT false,
  	"cdn_events_create" boolean DEFAULT false,
  	"cdn_events_update" boolean DEFAULT false,
  	"cdn_events_delete" boolean DEFAULT false,
  	"domain_reseller_products_find" boolean DEFAULT false,
  	"domain_reseller_products_create" boolean DEFAULT false,
  	"domain_reseller_products_update" boolean DEFAULT false,
  	"domain_reseller_products_delete" boolean DEFAULT false,
  	"reseller_domains_find" boolean DEFAULT false,
  	"reseller_domains_create" boolean DEFAULT false,
  	"reseller_domains_update" boolean DEFAULT false,
  	"reseller_domains_delete" boolean DEFAULT false,
  	"reseller_domain_operations_find" boolean DEFAULT false,
  	"reseller_domain_operations_create" boolean DEFAULT false,
  	"reseller_domain_operations_update" boolean DEFAULT false,
  	"reseller_domain_operations_delete" boolean DEFAULT false,
  	"reseller_domain_events_find" boolean DEFAULT false,
  	"reseller_domain_events_create" boolean DEFAULT false,
  	"reseller_domain_events_update" boolean DEFAULT false,
  	"reseller_domain_events_delete" boolean DEFAULT false,
  	"plans_find" boolean DEFAULT false,
  	"plans_create" boolean DEFAULT false,
  	"plans_update" boolean DEFAULT false,
  	"plans_delete" boolean DEFAULT false,
  	"subscriptions_find" boolean DEFAULT false,
  	"subscriptions_create" boolean DEFAULT false,
  	"subscriptions_update" boolean DEFAULT false,
  	"subscriptions_delete" boolean DEFAULT false,
  	"invoices_find" boolean DEFAULT false,
  	"invoices_create" boolean DEFAULT false,
  	"invoices_update" boolean DEFAULT false,
  	"invoices_delete" boolean DEFAULT false,
  	"site_entitlements_find" boolean DEFAULT false,
  	"site_entitlements_create" boolean DEFAULT false,
  	"site_entitlements_update" boolean DEFAULT false,
  	"site_entitlements_delete" boolean DEFAULT false,
  	"usage_records_find" boolean DEFAULT false,
  	"usage_records_create" boolean DEFAULT false,
  	"usage_records_update" boolean DEFAULT false,
  	"usage_records_delete" boolean DEFAULT false,
  	"central_entitlement_projections_find" boolean DEFAULT false,
  	"central_entitlement_projections_create" boolean DEFAULT false,
  	"central_entitlement_projections_update" boolean DEFAULT false,
  	"central_entitlement_projections_delete" boolean DEFAULT false,
  	"billing_usage_outbox_find" boolean DEFAULT false,
  	"billing_usage_outbox_create" boolean DEFAULT false,
  	"billing_usage_outbox_update" boolean DEFAULT false,
  	"billing_usage_outbox_delete" boolean DEFAULT false,
  	"billing_usage_samples_find" boolean DEFAULT false,
  	"billing_usage_samples_create" boolean DEFAULT false,
  	"billing_usage_samples_update" boolean DEFAULT false,
  	"billing_usage_samples_delete" boolean DEFAULT false,
  	"billing_storage_accounts_find" boolean DEFAULT false,
  	"billing_storage_accounts_create" boolean DEFAULT false,
  	"billing_storage_accounts_update" boolean DEFAULT false,
  	"billing_storage_accounts_delete" boolean DEFAULT false,
  	"billing_service_credentials_find" boolean DEFAULT false,
  	"billing_service_credentials_create" boolean DEFAULT false,
  	"billing_service_credentials_update" boolean DEFAULT false,
  	"billing_service_credentials_delete" boolean DEFAULT false,
  	"billing_replay_nonces_find" boolean DEFAULT false,
  	"billing_replay_nonces_create" boolean DEFAULT false,
  	"billing_replay_nonces_update" boolean DEFAULT false,
  	"billing_replay_nonces_delete" boolean DEFAULT false,
  	"feature_flags_find" boolean DEFAULT false,
  	"feature_flags_create" boolean DEFAULT false,
  	"feature_flags_update" boolean DEFAULT false,
  	"feature_flags_delete" boolean DEFAULT false,
  	"plugins_find" boolean DEFAULT false,
  	"plugins_create" boolean DEFAULT false,
  	"plugins_update" boolean DEFAULT false,
  	"plugins_delete" boolean DEFAULT false,
  	"theme_packages_find" boolean DEFAULT false,
  	"theme_packages_create" boolean DEFAULT false,
  	"theme_packages_update" boolean DEFAULT false,
  	"theme_packages_delete" boolean DEFAULT false,
  	"theme_artifacts_find" boolean DEFAULT false,
  	"theme_artifacts_create" boolean DEFAULT false,
  	"theme_artifacts_update" boolean DEFAULT false,
  	"theme_artifacts_delete" boolean DEFAULT false,
  	"deploy_targets_find" boolean DEFAULT false,
  	"deploy_targets_create" boolean DEFAULT false,
  	"deploy_targets_update" boolean DEFAULT false,
  	"deploy_targets_delete" boolean DEFAULT false,
  	"site_deployments_find" boolean DEFAULT false,
  	"site_deployments_create" boolean DEFAULT false,
  	"site_deployments_update" boolean DEFAULT false,
  	"site_deployments_delete" boolean DEFAULT false,
  	"theme_bindings_find" boolean DEFAULT false,
  	"theme_bindings_create" boolean DEFAULT false,
  	"theme_bindings_update" boolean DEFAULT false,
  	"theme_bindings_delete" boolean DEFAULT false,
  	"site_theme_settings_find" boolean DEFAULT false,
  	"site_theme_settings_create" boolean DEFAULT false,
  	"site_theme_settings_update" boolean DEFAULT false,
  	"site_theme_settings_delete" boolean DEFAULT false,
  	"webhooks_find" boolean DEFAULT false,
  	"webhooks_create" boolean DEFAULT false,
  	"webhooks_update" boolean DEFAULT false,
  	"webhooks_delete" boolean DEFAULT false,
  	"webhook_deliveries_find" boolean DEFAULT false,
  	"webhook_deliveries_create" boolean DEFAULT false,
  	"webhook_deliveries_update" boolean DEFAULT false,
  	"webhook_deliveries_delete" boolean DEFAULT false,
  	"audit_log_find" boolean DEFAULT false,
  	"audit_log_create" boolean DEFAULT false,
  	"audit_log_update" boolean DEFAULT false,
  	"audit_log_delete" boolean DEFAULT false,
  	"redirects_find" boolean DEFAULT false,
  	"redirects_create" boolean DEFAULT false,
  	"redirects_update" boolean DEFAULT false,
  	"redirects_delete" boolean DEFAULT false,
  	"forms_find" boolean DEFAULT false,
  	"forms_create" boolean DEFAULT false,
  	"forms_update" boolean DEFAULT false,
  	"forms_delete" boolean DEFAULT false,
  	"form_submissions_find" boolean DEFAULT false,
  	"form_submissions_create" boolean DEFAULT false,
  	"form_submissions_update" boolean DEFAULT false,
  	"form_submissions_delete" boolean DEFAULT false,
  	"search_find" boolean DEFAULT false,
  	"search_create" boolean DEFAULT false,
  	"search_update" boolean DEFAULT false,
  	"search_delete" boolean DEFAULT false,
  	"payload_folders_find" boolean DEFAULT false,
  	"payload_folders_create" boolean DEFAULT false,
  	"payload_folders_update" boolean DEFAULT false,
  	"payload_folders_delete" boolean DEFAULT false,
  	"domain_reseller_find" boolean DEFAULT false,
  	"domain_reseller_update" boolean DEFAULT false,
  	"payments_find" boolean DEFAULT false,
  	"payments_update" boolean DEFAULT false,
  	"platform_settings_find" boolean DEFAULT false,
  	"platform_settings_update" boolean DEFAULT false,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"enable_a_p_i_key" boolean,
  	"api_key" varchar,
  	"api_key_index" varchar
  );


  ALTER TABLE "payload_preferences_rels" ADD COLUMN "payload_mcp_api_keys_id" uuid;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "payload_mcp_api_keys_id" uuid;
  ALTER TABLE "payload_mcp_api_keys" ADD CONSTRAINT "payload_mcp_api_keys_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "payload_mcp_api_keys_user_idx" ON "payload_mcp_api_keys" USING btree ("user_id");
  CREATE INDEX "payload_mcp_api_keys_updated_at_idx" ON "payload_mcp_api_keys" USING btree ("updated_at");
  CREATE INDEX "payload_mcp_api_keys_created_at_idx" ON "payload_mcp_api_keys" USING btree ("created_at");
  ALTER TABLE "payload_preferences_rels" ADD CONSTRAINT "payload_preferences_rels_payload_mcp_api_keys_fk" FOREIGN KEY ("payload_mcp_api_keys_id") REFERENCES "public"."payload_mcp_api_keys"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_payload_mcp_api_keys_fk" FOREIGN KEY ("payload_mcp_api_keys_id") REFERENCES "public"."payload_mcp_api_keys"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "payload_preferences_rels_payload_mcp_api_keys_id_idx" ON "payload_preferences_rels" USING btree ("payload_mcp_api_keys_id");
  CREATE INDEX "payload_locked_documents_rels_payload_mcp_api_keys_id_idx" ON "payload_locked_documents_rels" USING btree ("payload_mcp_api_keys_id");
  `)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`

  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_payload_mcp_api_keys_fk";
  ALTER TABLE "payload_preferences_rels" DROP CONSTRAINT IF EXISTS "payload_preferences_rels_payload_mcp_api_keys_fk";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_payload_mcp_api_keys_id_idx";
  DROP INDEX IF EXISTS "payload_preferences_rels_payload_mcp_api_keys_id_idx";
  DROP INDEX IF EXISTS "payload_mcp_api_keys_created_at_idx";
  DROP INDEX IF EXISTS "payload_mcp_api_keys_updated_at_idx";
  DROP INDEX IF EXISTS "payload_mcp_api_keys_user_idx";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN IF EXISTS "payload_mcp_api_keys_id";
  ALTER TABLE "payload_preferences_rels" DROP COLUMN IF EXISTS "payload_mcp_api_keys_id";
  DROP TABLE IF EXISTS "payload_mcp_api_keys";

  `)
}
