import type { GlobalSlug } from 'payload'

/**
 * Collections exposed to MCP clients (see `src/plugins/mcp.ts`).
 * Exported for tests — keep in sync with the plugin config.
 */
export const MCP_COLLECTION_SLUGS = [
  'pages',
  'posts',
  'media',
  'categories',
  'users',
  'sites',
  'api-keys',
  'storage-connections',
  'theme',
  'site-branding',
  'header',
  'footer',
  'products',
  'orders',
  'store',
  'payment-gateways',
  'cdn-zones',
  'cdn-events',
  'domain-reseller-products',
  'reseller-domains',
  'reseller-domain-operations',
  'reseller-domain-events',
  'plans',
  'subscriptions',
  'invoices',
  'site-entitlements',
  'usage-records',
  'central-entitlement-projections',
  'billing-usage-outbox',
  'billing-usage-samples',
  'billing-storage-accounts',
  'billing-service-credentials',
  'billing-replay-nonces',
  'feature-flags',
  'plugins',
  'theme-packages',
  'theme-artifacts',
  'deploy-targets',
  'site-deployments',
  'theme-bindings',
  'site-theme-settings',
  'webhooks',
  'webhook-deliveries',
  'audit-log',
  'redirects',
  'forms',
  'form-submissions',
  'search',
  'payload-folders',
] as const

export const MCP_GLOBAL_SLUGS: GlobalSlug[] = ['domain-reseller', 'payments', 'platform-settings']
